<style>
    .card {
        border: 1px solid #ccc;
        border-radius: 5px;
        padding: 20px;
        margin: 10px;
        width: 300px;
        box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
    }

    .card img {
        max-width: 100%;
        height: auto;
    }

    .card h3 {
        font-size: 18px;
        margin-top: 10px;
    }

    .card h3:hover{
        text-decoration: none;
    }

    .card p {
        margin-top: 10px;
    }

    .heading{
        font-size: 25px;
        margin: 10px;
        text-align: center;
    }
    .sub-heading{
        font-size: 25px;
        color: blue;
    }
</style>
<div class="heading">
    Featured
    <span class="sub-heading">Brands</span>
</div>
<div style="display:flex; margin-bottom: 3rem;">
    <?php foreach ($this->getBrands() as $brand) : ?>
    <div class="card">
        <a href="<?php  echo $this->getRewriteUrl($brand);  ?>">
            <img src="<?php echo Mage::getBaseUrl('media').'/'.$brand->image; ?>" alt="Brand 1">
        </a>
        <h3><center><?php echo $brand->name; ?></center></h3>
    </div>
    <?php endforeach; ?>
</div>